version: "3.7"
services:
  myproject-todoapi-1:
    container_name: my-todoapi-1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:80"
    volumes:
      - ./appsettings.json:/app/appsettings.json

  myproject-todoapi-2:
    container_name: my-todoapi-2
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5002:80"
    volumes:
      - ./appsettings.json:/app/appsettings.json

  myproject-todoapi-3:
    container_name: my-todoapi-3
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5003:80"
    volumes:
      - ./appsettings.json:/app/appsettings.json
      
  myproject-nginx:
    container_name: my-nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf

  myproject-redis:
    container_name: my-redis
    image: redis
    restart: always
    ports:
      - "6379:80"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
